version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vehicles-db
    environment:
      POSTGRES_USER: vehicles_user
      POSTGRES_PASSWORD: vehicles_pass
      POSTGRES_DB: vehiclesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vehicles_user -d vehiclesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: